

// set variable for math Facts category
let mathFacts1 = document.getElementsByClassName('mathFacts1')[0];
let mathFacts2 = document.getElementsByClassName('mathFacts2')[0];
let mathFacts3 = document.getElementsByClassName('mathFacts3')[0];
let mathFacts4 = document.getElementsByClassName('mathFacts4')[0];
let mathFacts5 = document.getElementsByClassName('mathFacts5')[0];
let mathFacts6 = document.getElementsByClassName('mathFacts6')[0];
let mathFacts7 = document.getElementsByClassName('mathFacts7')[0];
let mathFacts8 = document.getElementsByClassName('mathFacts8')[0];
let mathFacts9 = document.getElementsByClassName('mathFacts9')[0];
let mathFacts10 = document.getElementsByClassName('mathFacts10')[0];
let mathFacts11 = document.getElementsByClassName('mathFacts1')[1];
let mathFacts12 = document.getElementsByClassName('mathFacts2')[1];
let mathFacts13 = document.getElementsByClassName('mathFacts3')[1];
let mathFacts14 = document.getElementsByClassName('mathFacts4')[1];
let mathFacts15 = document.getElementsByClassName('mathFacts5')[1];
let mathFacts16 = document.getElementsByClassName('mathFacts6')[1];
let mathFacts17 = document.getElementsByClassName('mathFacts7')[1];
let mathFacts18 = document.getElementsByClassName('mathFacts8')[1];
let mathFacts19 = document.getElementsByClassName('mathFacts9')[1];
let mathFacts20 = document.getElementsByClassName('mathFacts10')[1];
let mathFacts21 = document.getElementsByClassName('mathFacts1')[2];
let mathFacts22 = document.getElementsByClassName('mathFacts2')[2];
let mathFacts23 = document.getElementsByClassName('mathFacts3')[2];
let mathFacts24 = document.getElementsByClassName('mathFacts4')[2];
let mathFacts25 = document.getElementsByClassName('mathFacts5')[2];
let mathFacts26 = document.getElementsByClassName('mathFacts6')[2];
let mathFacts27 = document.getElementsByClassName('mathFacts7')[2];
let mathFacts28 = document.getElementsByClassName('mathFacts8')[2];
let mathFacts29 = document.getElementsByClassName('mathFacts9')[2];
let mathFacts30 = document.getElementsByClassName('mathFacts10')[2];
let mathFacts31 = document.getElementsByClassName('mathFacts1')[3];
let mathFacts32 = document.getElementsByClassName('mathFacts2')[3];
let mathFacts33 = document.getElementsByClassName('mathFacts3')[3];
let mathFacts34 = document.getElementsByClassName('mathFacts4')[3];
let mathFacts35 = document.getElementsByClassName('mathFacts5')[3];
let mathFacts36 = document.getElementsByClassName('mathFacts6')[3];
let mathFacts37 = document.getElementsByClassName('mathFacts7')[3];
let mathFacts38 = document.getElementsByClassName('mathFacts8')[3];
let mathFacts39 = document.getElementsByClassName('mathFacts9')[3];
let mathFacts40 = document.getElementsByClassName('mathFacts10')[3];
let mathFacts41 = document.getElementsByClassName('mathFacts1')[4];
let mathFacts42 = document.getElementsByClassName('mathFacts2')[4];
let mathFacts43 = document.getElementsByClassName('mathFacts3')[4];
let mathFacts44 = document.getElementsByClassName('mathFacts4')[4];
let mathFacts45 = document.getElementsByClassName('mathFacts5')[4];
let mathFacts46 = document.getElementsByClassName('mathFacts6')[4];
let mathFacts47 = document.getElementsByClassName('mathFacts7')[4];
let mathFacts48 = document.getElementsByClassName('mathFacts8')[4];
let mathFacts49 = document.getElementsByClassName('mathFacts9')[4];
let mathFacts50 = document.getElementsByClassName('mathFacts10')[4];
let mathFacts51 = document.getElementsByClassName('mathFacts1')[5];
let mathFacts52 = document.getElementsByClassName('mathFacts2')[5];
let mathFacts53 = document.getElementsByClassName('mathFacts3')[5];
let mathFacts54 = document.getElementsByClassName('mathFacts4')[5];
let mathFacts55 = document.getElementsByClassName('mathFacts5')[5];
let mathFacts56 = document.getElementsByClassName('mathFacts6')[5];
let mathFacts57 = document.getElementsByClassName('mathFacts7')[5];
let mathFacts58 = document.getElementsByClassName('mathFacts8')[5];
let mathFacts59 = document.getElementsByClassName('mathFacts9')[5];
let mathFacts60 = document.getElementsByClassName('mathFacts10')[5];
let mathFacts61 = document.getElementsByClassName('mathFacts1')[6];
let mathFacts62 = document.getElementsByClassName('mathFacts2')[6];
let mathFacts63 = document.getElementsByClassName('mathFacts3')[6];
let mathFacts64 = document.getElementsByClassName('mathFacts4')[6];
let mathFacts65 = document.getElementsByClassName('mathFacts5')[6];
let mathFacts66 = document.getElementsByClassName('mathFacts6')[6];
let mathFacts67 = document.getElementsByClassName('mathFacts7')[6];
let mathFacts68 = document.getElementsByClassName('mathFacts8')[6];
let mathFacts69 = document.getElementsByClassName('mathFacts9')[6];
let mathFacts70 = document.getElementsByClassName('mathFacts10')[6];
let mathFacts71 = document.getElementsByClassName('mathFacts1')[7];
let mathFacts72 = document.getElementsByClassName('mathFacts2')[7];
let mathFacts73 = document.getElementsByClassName('mathFacts3')[7];
let mathFacts74 = document.getElementsByClassName('mathFacts4')[7];
let mathFacts75 = document.getElementsByClassName('mathFacts5')[7];
let mathFacts76 = document.getElementsByClassName('mathFacts6')[7];
let mathFacts77 = document.getElementsByClassName('mathFacts7')[7];
let mathFacts78 = document.getElementsByClassName('mathFacts8')[7];
let mathFacts79 = document.getElementsByClassName('mathFacts9')[7];
let mathFacts80 = document.getElementsByClassName('mathFacts10')[7];
let mathFacts81 = document.getElementsByClassName('mathFacts1')[8];
let mathFacts82 = document.getElementsByClassName('mathFacts2')[8];
let mathFacts83 = document.getElementsByClassName('mathFacts3')[8];
let mathFacts84 = document.getElementsByClassName('mathFacts4')[8];
let mathFacts85 = document.getElementsByClassName('mathFacts5')[8];
let mathFacts86 = document.getElementsByClassName('mathFacts6')[8];
let mathFacts87 = document.getElementsByClassName('mathFacts7')[8];
let mathFacts88 = document.getElementsByClassName('mathFacts8')[8];
let mathFacts89 = document.getElementsByClassName('mathFacts9')[8];
let mathFacts90 = document.getElementsByClassName('mathFacts10')[8];
let mathFacts91 = document.getElementsByClassName('mathFacts1')[9];
let mathFacts92 = document.getElementsByClassName('mathFacts2')[9];
let mathFacts93 = document.getElementsByClassName('mathFacts3')[9];
let mathFacts94 = document.getElementsByClassName('mathFacts4')[9];
let mathFacts95 = document.getElementsByClassName('mathFacts5')[9];
let mathFacts96 = document.getElementsByClassName('mathFacts6')[9];
let mathFacts97 = document.getElementsByClassName('mathFacts7')[9];
let mathFacts98 = document.getElementsByClassName('mathFacts8')[9];
let mathFacts99 = document.getElementsByClassName('mathFacts9')[9];
let mathFacts100 = document.getElementsByClassName('mathFacts10')[9];

let mathSymbol1 = document.getElementsByClassName('mathSymbol1')[0];
let mathSymbol2 = document.getElementsByClassName('mathSymbol2')[0];
let mathSymbol3 = document.getElementsByClassName('mathSymbol3')[0];
let mathSymbol4 = document.getElementsByClassName('mathSymbol4')[0];
let mathSymbol5 = document.getElementsByClassName('mathSymbol5')[0];
let mathSymbol6 = document.getElementsByClassName('mathSymbol6')[0];
let mathSymbol7 = document.getElementsByClassName('mathSymbol7')[0];
let mathSymbol8 = document.getElementsByClassName('mathSymbol8')[0];
let mathSymbol9 = document.getElementsByClassName('mathSymbol9')[0];
let mathSymbol10 = document.getElementsByClassName('mathSymbol10')[0];
let mathSymbol11 = document.getElementsByClassName('mathSymbol11')[0];
let mathSymbol12 = document.getElementsByClassName('mathSymbol12')[0];
let mathSymbol13 = document.getElementsByClassName('mathSymbol13')[0];
let mathSymbol14 = document.getElementsByClassName('mathSymbol14')[0];
let mathSymbol15 = document.getElementsByClassName('mathSymbol15')[0];
let mathSymbol16 = document.getElementsByClassName('mathSymbol16')[0];
let mathSymbol17 = document.getElementsByClassName('mathSymbol17')[0];
let mathSymbol18 = document.getElementsByClassName('mathSymbol18')[0];
let mathSymbol19 = document.getElementsByClassName('mathSymbol19')[0];
let mathSymbol20 = document.getElementsByClassName('mathSymbol20')[0];
let mathSymbol21 = document.getElementsByClassName('mathSymbol21')[0];
let mathSymbol22 = document.getElementsByClassName('mathSymbol22')[0];
let mathSymbol23 = document.getElementsByClassName('mathSymbol23')[0];
let mathSymbol24 = document.getElementsByClassName('mathSymbol24')[0];
let mathSymbol25 = document.getElementsByClassName('mathSymbol25')[0];
let mathSymbol26 = document.getElementsByClassName('mathSymbol26')[0];
let mathSymbol27 = document.getElementsByClassName('mathSymbol27')[0];
let mathSymbol28 = document.getElementsByClassName('mathSymbol28')[0];
let mathSymbol29 = document.getElementsByClassName('mathSymbol29')[0];
let mathSymbol30 = document.getElementsByClassName('mathSymbol30')[0];
let mathSymbol31 = document.getElementsByClassName('mathSymbol31')[0];
let mathSymbol32 = document.getElementsByClassName('mathSymbol32')[0];
let mathSymbol33 = document.getElementsByClassName('mathSymbol33')[0];
let mathSymbol34 = document.getElementsByClassName('mathSymbol34')[0];
let mathSymbol35 = document.getElementsByClassName('mathSymbol35')[0];
let mathSymbol36 = document.getElementsByClassName('mathSymbol36')[0];
let mathSymbol37 = document.getElementsByClassName('mathSymbol37')[0];
let mathSymbol38 = document.getElementsByClassName('mathSymbol38')[0];
let mathSymbol39 = document.getElementsByClassName('mathSymbol39')[0];
let mathSymbol40 = document.getElementsByClassName('mathSymbol40')[0];
let mathSymbol41 = document.getElementsByClassName('mathSymbol41')[0];
let mathSymbol42 = document.getElementsByClassName('mathSymbol42')[0];
let mathSymbol43 = document.getElementsByClassName('mathSymbol43')[0];
let mathSymbol44 = document.getElementsByClassName('mathSymbol44')[0];
let mathSymbol45 = document.getElementsByClassName('mathSymbol45')[0];
let mathSymbol46 = document.getElementsByClassName('mathSymbol46')[0];
let mathSymbol47 = document.getElementsByClassName('mathSymbol47')[0];
let mathSymbol48 = document.getElementsByClassName('mathSymbol48')[0];
let mathSymbol49 = document.getElementsByClassName('mathSymbol49')[0];
let mathSymbol50 = document.getElementsByClassName('mathSymbol50')[0];

// listen for clicks on the increment button
// increment the count variable when the button is clicked
// change the count-el in the HTML to reflect the new count


function generateMultiplication() {
    mathFacts1.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts2.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts3.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts4.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts5.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts6.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts7.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts8.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts9.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts10.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts11.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts12.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts13.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts14.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts15.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts16.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts17.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts18.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts19.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts20.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts21.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts22.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts23.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts24.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts25.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts26.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts27.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts28.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts29.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts30.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts31.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts32.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts33.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts34.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts35.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts36.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts37.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts38.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts39.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts40.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts41.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts42.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts43.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts44.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts45.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts46.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts47.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts48.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts49.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts50.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts51.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts52.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts53.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts54.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts55.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts56.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts57.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts58.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts59.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts60.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts61.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts62.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts63.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts64.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts65.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts66.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts67.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts68.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts69.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts70.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts71.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts72.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts73.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts74.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts75.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts76.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts77.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts78.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts79.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts80.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts81.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts82.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts83.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts84.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts85.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts86.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts87.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts88.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts89.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts90.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
    mathFacts91.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts92.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts93.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts94.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts95.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts96.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts97.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts98.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts99.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts100.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	
	
	//Change the symbol for multiplication problems to x
	mathSymbol1.innerText = 'x'
	mathSymbol2.innerText = 'x'
	mathSymbol3.innerText = 'x'
	mathSymbol4.innerText = 'x'
	mathSymbol5.innerText = 'x'
	mathSymbol6.innerText = 'x'
	mathSymbol7.innerText = 'x'
	mathSymbol8.innerText = 'x'
	mathSymbol9.innerText = 'x'
	mathSymbol10.innerText = 'x'
	mathSymbol11.innerText = 'x'
	mathSymbol12.innerText = 'x'
	mathSymbol13.innerText = 'x'
	mathSymbol14.innerText = 'x'
	mathSymbol15.innerText = 'x'
	mathSymbol16.innerText = 'x'
	mathSymbol17.innerText = 'x'
	mathSymbol18.innerText = 'x'
	mathSymbol19.innerText = 'x'
	mathSymbol20.innerText = 'x'
	mathSymbol21.innerText = 'x'
	mathSymbol22.innerText = 'x'
	mathSymbol23.innerText = 'x'
	mathSymbol24.innerText = 'x'
	mathSymbol25.innerText = 'x'
	mathSymbol26.innerText = 'x'
	mathSymbol27.innerText = 'x'
	mathSymbol28.innerText = 'x'
	mathSymbol29.innerText = 'x'
	mathSymbol30.innerText = 'x'
	mathSymbol31.innerText = 'x'
	mathSymbol32.innerText = 'x'
	mathSymbol33.innerText = 'x'
	mathSymbol34.innerText = 'x'
	mathSymbol35.innerText = 'x'
	mathSymbol36.innerText = 'x'
	mathSymbol37.innerText = 'x'
	mathSymbol38.innerText = 'x'
	mathSymbol39.innerText = 'x'
	mathSymbol40.innerText = 'x'
	mathSymbol41.innerText = 'x'
	mathSymbol42.innerText = 'x'
	mathSymbol43.innerText = 'x'
	mathSymbol44.innerText = 'x'
	mathSymbol45.innerText = 'x'
	mathSymbol46.innerText = 'x'
	mathSymbol47.innerText = 'x'
	mathSymbol48.innerText = 'x'
	mathSymbol49.innerText = 'x'
	mathSymbol50 .innerText= 'x'
}

function generateDivision() {
    mathFacts1.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts2.innerText = mathFacts1.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts3.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts4.innerText = mathFacts3.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts5.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts6.innerText = mathFacts5.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts7.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts8.innerText = mathFacts7.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts9.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts10.innerText = mathFacts9.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts11.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts12.innerText = mathFacts11.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts13.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts14.innerText = mathFacts13.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts15.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts16.innerText = mathFacts15.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts17.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts18.innerText = mathFacts17.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts19.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts20.innerText = mathFacts19.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts21.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts22.innerText = mathFacts21.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts23.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts24.innerText = mathFacts23.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts25.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts26.innerText = mathFacts25.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts27.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts28.innerText = mathFacts27.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts29.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts30.innerText = mathFacts29.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts31.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts32.innerText = mathFacts31.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts33.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts34.innerText = mathFacts33.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts35.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts36.innerText = mathFacts35.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts37.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts38.innerText = mathFacts37.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts39.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts40.innerText = mathFacts39.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts41.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts42.innerText = mathFacts41.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts43.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts44.innerText = mathFacts43.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts45.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts46.innerText = mathFacts45.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts47.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts48.innerText = mathFacts47.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts49.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts50.innerText = mathFacts49.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts51.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts52.innerText = mathFacts51.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts53.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts54.innerText = mathFacts53.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts55.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts56.innerText = mathFacts55.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts57.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts58.innerText = mathFacts57.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts59.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts60.innerText = mathFacts59.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts61.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts62.innerText = mathFacts61.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts63.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts64.innerText = mathFacts63.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts65.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts66.innerText = mathFacts65.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts67.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts68.innerText = mathFacts67.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts69.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts70.innerText = mathFacts69.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts71.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts72.innerText = mathFacts71.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts73.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts74.innerText = mathFacts73.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts75.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts76.innerText = mathFacts75.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts77.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts78.innerText = mathFacts77.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts79.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts80.innerText = mathFacts79.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts81.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts82.innerText = mathFacts81.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts83.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts84.innerText = mathFacts83.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts85.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts86.innerText = mathFacts85.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts87.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts88.innerText = mathFacts87.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts89.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts90.innerText = mathFacts89.innerText * Math.floor(Math.random() * (9 - 1)+1);
    mathFacts91.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts92.innerText = mathFacts91.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts93.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts94.innerText = mathFacts93.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts95.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts96.innerText = mathFacts95.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts97.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts98.innerText = mathFacts97.innerText * Math.floor(Math.random() * (9 - 1)+1);
	mathFacts99.innerText = Math.floor(Math.random() * (9 - 1)) + 1;
	mathFacts100.innerText = mathFacts99.innerText * Math.floor(Math.random() * (9 - 1)+1);
	
	
	//Change the symbol for multiplication problems to ÷
	
	mathSymbol1.innerText = '÷'
	mathSymbol2.innerText = '÷'
	mathSymbol3.innerText = '÷'
	mathSymbol4.innerText = '÷'
	mathSymbol5.innerText = '÷'
	mathSymbol6.innerText = '÷'
	mathSymbol7.innerText = '÷'
	mathSymbol8.innerText = '÷'
	mathSymbol9.innerText = '÷'
	mathSymbol10.innerText = '÷'
	mathSymbol11.innerText = '÷'
	mathSymbol12.innerText = '÷'
	mathSymbol13.innerText = '÷'
	mathSymbol14.innerText = '÷'
	mathSymbol15.innerText = '÷'
	mathSymbol16.innerText = '÷'
	mathSymbol17.innerText = '÷'
	mathSymbol18.innerText = '÷'
	mathSymbol19.innerText = '÷'
	mathSymbol20.innerText = '÷'
	mathSymbol21.innerText = '÷'
	mathSymbol22.innerText = '÷'
	mathSymbol23.innerText = '÷'
	mathSymbol24.innerText = '÷'
	mathSymbol25.innerText = '÷'
	mathSymbol26.innerText = '÷'
	mathSymbol27.innerText = '÷'
	mathSymbol28.innerText = '÷'
	mathSymbol29.innerText = '÷'
	mathSymbol30.innerText = '÷'
	mathSymbol31.innerText = '÷'
	mathSymbol32.innerText = '÷'
	mathSymbol33.innerText = '÷'
	mathSymbol34.innerText = '÷'
	mathSymbol35.innerText = '÷'
	mathSymbol36.innerText = '÷'
	mathSymbol37.innerText = '÷'
	mathSymbol38.innerText = '÷'
	mathSymbol39.innerText = '÷'
	mathSymbol40.innerText = '÷'
	mathSymbol41.innerText = '÷'
	mathSymbol42.innerText = '÷'
	mathSymbol43.innerText = '÷'
	mathSymbol44.innerText = '÷'
	mathSymbol45.innerText = '÷'
	mathSymbol46.innerText = '÷'
	mathSymbol47.innerText = '÷'
	mathSymbol48.innerText = '÷'
	mathSymbol49.innerText = '÷'
	mathSymbol50 .innerText= '÷'
}